# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 05:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=10)),
                ('ads', models.CharField(max_length=100)),
                ('aphone', models.CharField(max_length=11)),
                ('atags', models.CharField(max_length=10, null=True)),
                ('isstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_father', models.CharField(max_length=10, verbose_name='父类别')),
            ],
        ),
        migrations.CreateModel(
            name='category_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subgrade_name', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.category')),
            ],
            options={
                'permissions': (('category_add', '添加类别'), ('category_modify', '修改类别'), ('category_delete', '删除类别'), ('category_check', '查看类别')),
            },
        ),
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commodity_name', models.CharField(max_length=50, verbose_name='商品名字')),
                ('describe', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('Stock', models.IntegerField(verbose_name='库存')),
                ('Sales_volumes', models.IntegerField(default=0, verbose_name='销售数量')),
                ('Commodity_img', models.ImageField(upload_to='./static/media/goods/', verbose_name='商品图片')),
                ('state', models.CharField(max_length=2, verbose_name='状态')),
                ('commodity_delete', models.BooleanField(default=0, verbose_name='商品逻辑删除')),
                ('Clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.category_Subcategory', verbose_name='商品类别')),
            ],
            options={
                'permissions': (('commodity_add', '添加商品'), ('commodity_modify', '修改商品'), ('commodity_delete', '删除商品'), ('commodity_check', '查看商品')),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consignee', models.CharField(max_length=10, verbose_name='收货人')),
                ('Receiving_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单价格')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('state', models.CharField(max_length=2, verbose_name='订单状态')),
            ],
            options={
                'permissions': (('Order_modify', '修改订单'), ('Order_delete', '删除订单'), ('Order_check', '查看订单')),
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.commodity')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.Order')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='账号')),
                ('email', models.CharField(max_length=50, null=True)),
                ('Phone', models.CharField(max_length=13, null=True, verbose_name='电话号码')),
                ('sex', models.CharField(blank=True, default=0, max_length=2, null=True, verbose_name='性别')),
                ('active', models.BooleanField(default=False)),
                ('headimage', models.ImageField(default='./static/media/img/1.jpg', upload_to='./static/media/goods/')),
                ('password', models.CharField(max_length=120)),
            ],
            options={
                'permissions': (('profile_add', '添加用户'), ('profile_modify', '修改用户'), ('profiledelete', '删除用户'), ('profile_check', '查看用户')),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.profile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.commodity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.profile'),
        ),
    ]
