# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0002_profile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
