# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0004_category_category_subcategory_commodity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='top_level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uid',
        ),
    ]
