# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0005_auto_20180823_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='Commodity_category',
            field=models.ManyToManyField(to='BC2_admin.category_Subcategory', verbose_name='商品类别'),
        ),
    ]
