# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0006_auto_20180824_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='Commodity_category',
        ),
        migrations.AddField(
            model_name='commodity',
            name='Commodity_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BC2_admin.category_Subcategory', verbose_name='商品类别'),
            preserve_default=False,
        ),
    ]
