# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0007_auto_20180824_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='Commodity_category',
            new_name='uid',
        ),
    ]
