# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0008_auto_20180824_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
