# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-25 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_admin', '0010_auto_20180826_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
