# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BC2_admin', '0012_auto_20180828_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=10)),
                ('ads', models.CharField(max_length=100)),
                ('aphone', models.CharField(max_length=11)),
                ('atags', models.CharField(max_length=10, null=True)),
                ('isstatus', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
