# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=0, max_length=1, verbose_name='状态'),
        ),
    ]
