# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Last',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
