# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_last'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Last',
            new_name='Last_login',
        ),
    ]
