# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180821_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='BC2_admin',
        ),
    ]
