# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 06:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10, verbose_name='类别名称')),
                ('uid', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commodity_name', models.CharField(max_length=50, verbose_name='商品名字')),
                ('describe', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('Stock', models.IntegerField(verbose_name='库存')),
                ('Sales_volumes', models.IntegerField(default=0, verbose_name='销售数量')),
                ('Commodity_img', models.ImageField(upload_to='./static/media/goods/', verbose_name='商品图片')),
                ('state', models.CharField(max_length=2, verbose_name='状态')),
                ('commodity_delete', models.BooleanField(default=0, verbose_name='商品逻辑删除')),
                ('Clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('Commodity_category', models.ManyToManyField(to='BC2_html.category', verbose_name='商品类别')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consignee', models.CharField(max_length=10, verbose_name='收货人')),
                ('Receiving_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('zip_code', models.CharField(max_length=6, verbose_name='邮编')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单价格')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('state', models.CharField(max_length=2, verbose_name='订单状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
