# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_Subcategory',
            field=models.CharField(default=1, max_length=10, verbose_name='子类别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=10, verbose_name='父类别'),
        ),
    ]
