# Generated by Django 2.0.5 on 2018-08-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='Commodity_name',
            field=models.CharField(max_length=50, verbose_name='商品名字'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格'),
        ),
    ]
