# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0002_auto_20180823_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category_father',
        ),
        migrations.AddField(
            model_name='category',
            name='top_level',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
