# Generated by Django 2.0.5 on 2018-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0002_auto_20180817_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='describe',
            field=models.CharField(max_length=100, verbose_name='商品描述'),
        ),
    ]
