# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0003_auto_20180823_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subgrade_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_Subcategory',
        ),
        migrations.AddField(
            model_name='category_subcategory',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC2_html.category'),
        ),
    ]
