# Generated by Django 2.0.5 on 2018-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0006_auto_20180817_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='Commodity_img',
            field=models.ImageField(upload_to='./static/media/goods/', verbose_name='商品图片'),
        ),
    ]
