# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 10:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0007_auto_20180819_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
