# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0008_auto_20180819_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='Clicks',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Sales_volumes',
            field=models.IntegerField(default=0, verbose_name='销售数量'),
        ),
    ]
