# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC2_html', '0009_auto_20180819_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_uid',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_delete',
            field=models.BooleanField(default=0, verbose_name='商品逻辑删除'),
        ),
    ]
